# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:12:21+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Path, Query
from pydantic import conint
from starlette.requests import Request

from models import (
    Error,
    ErrorLimit,
    Includes1,
    ProductGroupKeys,
    Sort,
    Subscription,
    SubscriptionList,
    SubscriptionUpdate,
    V1SubscriptionsProductGroupsGetResponse,
)

app = MCPProxy(
    title='',
    version='1.0.0',
    servers=[{'url': '//api.ote-godaddy.com'}],
)


@app.get(
    '/v1/subscriptions', tags=['subscription_management', 'product_group_management']
)
def list(
    x__shopper__id: Optional[str] = Header(None, alias='X-Shopper-Id'),
    x__market__id: Optional[str] = Header('en-US', alias='X-Market-Id'),
    product_group_keys: Optional[ProductGroupKeys] = Query(
        None, alias='productGroupKeys'
    ),
    includes: Optional[Includes1] = None,
    offset: Optional[int] = 0,
    limit: Optional[conint(ge=1, le=2000)] = 25,
    sort: Optional[Sort] = '-expiresAt',
):
    """
    Retrieve a list of Subscriptions for the specified Shopper
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/subscriptions/productGroups', tags=['product_group_management'])
def product_groups(
    x__shopper__id: Optional[str] = Header(None, alias='X-Shopper-Id'),
    x__market__id: Optional[str] = Header('en-US', alias='X-Market-Id'),
):
    """
    Retrieve a list of ProductGroups for the specified Shopper
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete('/v1/subscriptions/{subscriptionId}', tags=['subscription_management'])
def cancel(
    x__shopper__id: Optional[str] = Header(None, alias='X-Shopper-Id'),
    subscription_id: str = Path(..., alias='subscriptionId'),
):
    """
    Cancel the specified Subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v1/subscriptions/{subscriptionId}', tags=['subscription_management'])
def get(
    x__shopper__id: Optional[str] = Header(None, alias='X-Shopper-Id'),
    x__market__id: Optional[str] = Header('en-US', alias='X-Market-Id'),
    subscription_id: str = Path(..., alias='subscriptionId'),
):
    """
    Retrieve details for the specified Subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/v1/subscriptions/{subscriptionId}',
    description=""" Only Subscription properties that can be changed without immediate financial impact can be modified via PATCH, whereas some properties can be changed by purchasing a renewal<br/><strong>This endpoint only supports JWT authentication</strong> """,
    tags=['subscription_management'],
)
def update(
    subscription_id: str = Path(..., alias='subscriptionId'),
    body: SubscriptionUpdate = ...,
):
    """
    Update details for the specified Subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
