# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:12:21+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class ErrorField(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    message: Optional[str] = Field(
        None,
        description='Human-readable, English description of the problem with the contents of the field',
    )
    path: str = Field(
        ...,
        description="<ul>\n<li style='margin-left: 12px;'>JSONPath referring to a field containing an error</li>\n<strong style='margin-left: 12px;'>OR</strong>\n<li style='margin-left: 12px;'>JSONPath referring to a field that refers to an object containing an error, with more detail in `pathRelated`</li>\n</ul>",
    )
    pathRelated: Optional[str] = Field(
        None,
        description='JSONPath referring to a field containing an error, which is referenced by `path`',
    )


class ErrorLimit(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    fields: Optional[List[ErrorField]] = Field(
        None,
        description='List of the specific fields, and the errors found with their contents',
    )
    message: Optional[str] = Field(
        None, description='Human-readable, English description of the error'
    )
    retryAfterSec: int = Field(
        ..., description='Number of seconds to wait before attempting a similar request'
    )


class Pagination(BaseModel):
    first: Optional[str] = Field(None, description='URI to access the first page')
    last: Optional[str] = Field(None, description='URI to access the last page')
    next: Optional[str] = Field(None, description='URI to access the next page')
    previous: Optional[str] = Field(None, description='URI to access the previous page')
    total: Optional[int] = Field(None, description='Number of records available')


class ProductGroup(BaseModel):
    productGroupKey: str = Field(
        ..., description='Primary key of a grouping of related Subscriptions'
    )
    subscriptionCount: int = Field(
        ...,
        description='The number of Subscriptions that the shopper owns in this group',
    )


class Status(Enum):
    ACTIVE = 'ACTIVE'
    PENDING = 'PENDING'
    CANCELED = 'CANCELED'


class Commitment(Enum):
    PAID = 'PAID'
    FREE = 'FREE'
    TRIAL = 'TRIAL'


class SubscriptionAddon(BaseModel):
    commitment: Commitment = Field(
        ..., description='The financial commitment the customer has in the product'
    )
    pfid: int = Field(..., description='Unique identifier of the add-in product')
    quantity: int


class PastDueType(Enum):
    ADDON = 'ADDON'
    BURST = 'BURST'
    SUBSCRIPTION = 'SUBSCRIPTION'


class Status1(Enum):
    CURRENT = 'CURRENT'
    PAST_DUE = 'PAST_DUE'


class SubscriptionBilling(BaseModel):
    commitment: Commitment = Field(
        ..., description='The financial commitment the customer has in the product'
    )
    pastDueTypes: Optional[List[PastDueType]] = Field(
        None,
        description='The types of charges that are past due when `status` is PAST_DUE',
    )
    renewAt: str = Field(
        ...,
        description='The point in time after which the Subscription will bill for automatic renewal',
    )
    status: Status1 = Field(..., description='Whether payments are past due')


class RenewalPeriodUnit(Enum):
    MONTH = 'MONTH'
    QUARTER = 'QUARTER'
    SEMI_ANNUAL = 'SEMI_ANNUAL'
    YEAR = 'YEAR'


class SubscriptionProduct(BaseModel):
    label: str = Field(
        ...,
        description='A human readable description of the Product that is subscribed',
    )
    namespace: str = Field(..., description='Grouping of related Subscriptions')
    pfid: int = Field(
        ..., description='Unique identifier of the Product that is subscribed'
    )
    productGroupKey: str = Field(
        ..., description='Primary key of a grouping of related Subscriptions'
    )
    renewalPeriod: int = Field(
        ...,
        description='The number of `renewalPeriodUnits` that will be added by the `renewalPfid`',
    )
    renewalPeriodUnit: RenewalPeriodUnit = Field(
        ..., description='The unit of time that `renewalPeriod` is measured in'
    )
    renewalPfid: int = Field(
        ..., description='Unique identifier of the renewal Product'
    )
    supportBillOn: bool = Field(
        ...,
        description='Whether the product supports the `billOn` option on the renewal endpoint',
    )


class SubscriptionRelations(BaseModel):
    children: Optional[List[str]] = Field(
        None,
        description='A set of related Subscriptions that will be canceled automatically if this Subscription is canceled',
    )
    parent: Optional[str] = Field(
        None, description="Unique identifier of this Subscription's parent"
    )


class SubscriptionUpdate(BaseModel):
    paymentProfileId: Optional[int] = Field(
        None,
        description='Unique identifier of the payment profile you want to be used for automatic renewal',
    )
    renewAuto: Optional[bool] = Field(
        None, description='Whether or not you want the Subscription renew automatically'
    )


class Includes(Enum):
    addons = 'addons'
    relations = 'relations'


class Sort(Enum):
    expiresAt = 'expiresAt'
    field_expiresAt = '-expiresAt'


class ProductGroupKeys(RootModel[List[str]]):
    root: List[str]


class Includes1(RootModel[Union[List[str], Includes]]):
    root: Union[List[str], Includes]


class V1SubscriptionsProductGroupsGetResponse(RootModel[List[ProductGroup]]):
    root: List[ProductGroup]


class Error(BaseModel):
    code: str = Field(
        ...,
        description='Short identifier for the error, suitable for indicating the specific error within client code',
    )
    fields: Optional[List[ErrorField]] = Field(
        None,
        description='List of the specific fields, and the errors found with their contents',
    )
    message: Optional[str] = Field(
        None, description='Human-readable, English description of the error'
    )


class Subscription(BaseModel):
    addons: Optional[List[SubscriptionAddon]] = Field(
        None,
        description='An array of additional products that have been purchased to augment this Subscription',
    )
    billing: SubscriptionBilling
    cancelable: Optional[bool] = Field(
        None, description='Whether or not the Subscription is allowed to be canceled'
    )
    createdAt: str = Field(..., description='When the Subscription was created')
    expiresAt: Optional[str] = Field(
        None, description='When the Subscription will expire'
    )
    label: Optional[str] = Field(
        None, description='A human readable description of this Subscription'
    )
    launchUrl: Optional[str] = Field(
        None, description="The url to use or manage this Subscription's active product"
    )
    paymentProfileId: Optional[int] = Field(
        None,
        description='Unique identifier of the payment profile that will be used to automatically renew this Subscription',
    )
    priceLocked: bool = Field(
        ...,
        description='Whether the renewal price will be based from the list price or a locked-in price for this shopper',
    )
    product: SubscriptionProduct
    relations: Optional[SubscriptionRelations] = None
    renewAuto: bool = Field(
        ...,
        description='Whether or not the Subscription is set to be automatically renewed via the billing agent',
    )
    renewable: bool = Field(
        ..., description='Whether or not the Subscription is allowed to be renewed'
    )
    status: Status = Field(
        ...,
        description='Whether the Subscription is active or the specific non-active state',
    )
    subscriptionId: str = Field(
        ..., description='Unique identifier of the Subscription'
    )
    upgradeable: bool = Field(
        ..., description='Whether or not the Subscription is allowed to be upgraded'
    )


class SubscriptionList(BaseModel):
    pagination: Pagination
    subscriptions: List[Subscription] = Field(
        ..., description='A collection of subscriptions'
    )
